stages:          # List of stages for jobs, and their order of execution
  - build
  - test

build-job:       # This job runs in the build stage, which runs first.
  image: ${CI_REGISTRY}/steam/steamos-docker-images/jupiter-main/image-builder
  stage: build
  tags:
    - x86_64-linux-kvm-docker
  script:
    - pacman -Syu --noconfirm
    - pacman -S --noconfirm base-devel
    - pacman -S --noconfirm lv2 faust boost linux-api-headers qt5-base
    - FAUSTINC=/usr/include/faust make

unit-test-job:   # This job runs in the test stage.
  image: ${CI_REGISTRY}/steam/steamos-docker-images/jupiter-main/image-builder
  stage: test    # It only starts when the job in the build stage completes successfully.
  tags:
    - x86_64-linux-kvm-docker
  script:
    - pacman -Syu --noconfirm
    - pacman -S --noconfirm base-devel
    - pacman -S --noconfirm lv2 faust boost linux-api-headers qt5-base
    - FAUSTINC=/usr/include/faust make benchmark

